### ISSUE TITLE
Teacher model

### ISSUE THREAD

**Issue by Hou12378** [jida-thada/SKA#1]
https://drive.google.com/drive/folders/1guPbiUawDvVrkhZXQvMZPS4blGosZiWW?usp=sharing
The teacher model decompression error, please resend it, thank you.

**Comment by jida-thada** [comment]
That was the incorrect link. Sorry about that. Please check the new one in Readme. Thank you.

**Comment by Hou12378** [comment]
Thank you.&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jida-thada/SKA"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月13日(星期一) 晚上6:41
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jida-thada/SKA] Teacher model (#1)





 
That was the incorrect link. Sorry about that. Please check the new one in Readme. Thank you.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Hou12378** [comment]
Sorry，The teacher folder downloaded from the link in the Readme still shows: The compressed file is corrupted.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jida-thada/SKA"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月13日(星期一) 晚上6:41
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jida-thada/SKA] Teacher model (#1)





 
Closed #1.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
